[toolchain]
anchor_version = "0.29.0"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[[programs.devnet]]
name = "matrix_game"
address = "11111111111111111111111111111111"

[programs.localnet]
matrix_game = "11111111111111111111111111111111"

[scripts]
test = "yarn run ts-mocha --timeout 1000000 tests/**/*.ts"
